### ISSUE TITLE
Open wrong link when Soft Wrap enabled

### ISSUE THREAD

**Issue by vinhjaxt** [patrick96/click-link#11] opened 2017-07-07 20:08 UTC
Open wrong link when Soft Wrap enabled

If link is very long, click-link will open wrong link

**Comment by patrick96** [comment] 2017-07-08 10:51
Duplicate of #8 

If soft wrap is enabled and there are two links on adjacent lines, there is no way to figure out if they're part of the same link.

**Closed as completed by patrick96** 2017-07-08 10:51 UTC
Labels: duplicate
